language: cpp
sudo: required
#services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    #- build-essential
    - gcc-5
    - g++-5
    #- libogg-dev
    #- libmpeg2-4-dev
    #- libpqxx-dev
    #- libssl-dev
    #- libcrypto++-dev
    #- libpng-dev

#before_install:
  # download a static-built ffmpeg from the official website
  #- wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  #- tar -xf ffmpeg-release-64bit-static.tar.xz
  #- sudo cp ffmpeg-3.4.2-64bit-static/ffmpeg /usr/bin/
  #- sudo cp ffmpeg-3.4.2-64bit-static/ffprobe /usr/bin/

install:
  # upgrade gcc
  - sudo apt-get update -q
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 99
  # verify installed versions
  - g++ -v

script:
  - ./autogen.sh
  - ./configure
  - make -j3
  #- python python/setup.py bdist_wheel\
  #- pip install dist/mfc-*
  - echo 'run tests' # add test script here 
  - echo 'done' # distcheck V=1 || (cat puffer-0.2/_build/src/tests/test-suite.log && exit 1)

notifications:
  email: false
  #webhooks:
  #  - https://snr.zulipchat.com/api/v1/external/travis?api_key=AtzK5F9kaHRKDQKNbD4ujZCTQTm91B5j&stream=puffer-notification&topic=build-status
