language: cpp
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - nasm

before_install:

install:
  - uname -a
  - lsb_release -a
  # upgrade gcc
  - sudo apt-get update -q
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 99
  - g++ -v
  # upgrade python version
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y 
  - sudo apt-get update -q
  - sudo apt-get install --allow-unauthenticated python3.5-dev
  - sudo rm /usr/bin/python3
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python3
  - python3 --version
  - sudo apt-get install python3-pip 
  - sudo pip3 install --upgrade pip
  - pip3 --version
  # install python dependencies
  - sudo pip3 install numpy
  - sudo pip3 install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp35-cp35m-linux_x86_64.whl
  - sudo pip3 install cffi torchvision

script:
  - ./autogen.sh
  - ./configure
  - make -j3
  - ./python/install.sh
  - make check

notifications:
  email: false
