language: cpp
sudo: required
services: docker

before_install:
  - docker build -t nnfc-travis -f .travis.Dockerfile .

script:
  - docker run -ti nnfc-travis:latest /home/user/nnfc/.travis-check.sh

notifications:
  email: false
